### DISCUSSION TITLE
Task Abends with BGYSC0232E while Registering Objects in DBRC

### DISCUSSION THREAD

**Discussion by rohan-zos-ansible** [ansible-collections/ibm_zos_ims#139] [General]
I get below error while running commands for DBRC - any suggestions
fatal: [imsa]: FAILED! => {"changed": false, "dbrc_output": [], "msg": "BGYSC0232E Child process did not complete correctly for DSPURX00.\n", "rc": 255, "unformatted_output": [""]}

If i run job for DBRC registration then it works.

Ansible code -
- name: Register Catalog Databases to DBRC
  hosts: "{{ target_host | default('imsa') }}"
  collections:
  - ibm.ibm_zos_core
  - ibm.ibm_zos_ims
  environment: "{{ environment_vars }}"    
  vars_files:
    - /home/personal_path/host_vars/vars.yml
  tasks:       
    - name: Register Catalog Databases and Indexes to DBRC 
      ibm.ibm_zos_ims.ims_dbrc:
        command: 
          - DELETE.DB DBD(DFSCD000)
          - DELETE.DB DBD(DFSCX000)
          - INIT.DB   DBD(DFSCD000) TYPHALDB SHARELVL(3)
          - INIT.PART DBD(DFSCD000) PART(DFSCD01) DSNPREFX({{ DFS_IMS_HLQGROUP }}.DFSCD000) KEYSTRNG(X'FF') GENMAX(3)
          - INIT.DB DBD(DFSCX000) TYPHALDB SHARELVL(3)
          - INIT.PART DBD(DFSCX000) PART(DFSCX01) DSNPREFX({{ DFS_IMS_HLQGROUP }}.DFSCX000) KEYSTRNG(X'FF') GENMAX(3)
          - LIST.DB DBD(DFSCD000) DBDS
          - LIST.DB DBD(DFSCX000) DBDS
        steplib:
          - "{{ DFS_IMS_HLQGROUP2 }}.SDFSRESL"
          - BNB.IMSVS.R15.SDFSRESL          
        dbd_lib: "{{ DFS_IMS_HLQGROUP2 }}.DBDLIB"
        recon1: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.RECON1"
        recon2: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.RECON2"
        recon3: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.RECON3"

**Comment by ketankelkar** [comment]
Hi @rohan-zos-ansible, thanks for reaching out to us. Since your playbook task calls the `zos_ims_dbrc` module which is part of the `ibm_zos_ims` collection, we have decided to move this discussion over to the IMS Ansible team who are better suited to help you with IMS Ansible Issues

In the mean time, re-running your playbook with verbosity might surface what's going wrong, 
`ansible-playbook -i inventories playbook.yml -vvv`

**Comment by rohan-zos-ansible** [comment]
Thank you, also tried with -vvvv. But, seems same problem. I could see error message changed to "DBRC command(s) could not be processed. Please check input parameters." when I restored ims collection to 1.3.0 and upgraded zos_core to 1.10.0. 
Here is simplest form of DBRC task -
```
---
- name: Register with DBRC
  hosts: "{{ target_host | default('xxxx') }}"
  collections:
  - ibm.ibm_zos_ims
  environment: "{{ environment_vars }}"    
  vars_files:
    - /home/personal/Ansible_Test/ans_jcl_imsa_personal/host_vars/vars.yml
  tasks:       
    - name: Register IMS Catalog to DBRC 
      ibm.ibm_zos_ims.ims_dbrc:
        command: 
          - LIST.DB DBD(A0DBD)
        steplib:
          - "DBU.QA.VXOL.SDFSRESL"
          - "BNB.IMSVS.R15.SDFSRESL"  
        dbd_lib: "DBU.QA.VXOL.DBDLIB"
        recon1: "MVSRYT.VXOL.RECON1"
        recon2: "MVSRYT.VXOL.RECON2"
        recon3: "MVSRYT.VXOL.RECON3"
```
